name: Build & Deploy Docker Image

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t daily-rise-api:latest .

      - name: Save image to tar
        run: |
          docker save daily-rise-api:latest -o daily-rise-api.tar

      - name: Fix permissions
        run: chmod 644 daily-rise-api.tar

      - name: Upload image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "daily-rise-api.tar"
          target: /opt/daily-rise

      - name: Load & run on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /opt/daily-rise
            docker load -i daily-rise-api.tar
            docker compose up -d
